reference: "/tudelft.net/staff-umbrella/YeastVariantCalling/wsung/IMBvariant/reference/chromosomes/CEN.PK113-7D_chr01_pilon.fa"
name: "chr1"
mutations: 200
repeats: 10
props: [[0.5,0.5],[0.7,0.3],[0.9,0.1],[0.95,0.05],[0.98,0.02],[0.99,0.01]]
f_cov: [50]
working_dir: "/tudelft.net/staff-umbrella/YeastVariantCalling/wsung"
rename_file: "/tudelft.net/staff-umbrella/YeastVariantCalling/wsung/BEP_pipeline/config/rename_chr.txt"
varscan_filter: "/tudelft.net/staff-umbrella/YeastVariantCalling/wsung/BEP_pipeline/workflow/scripts/fpfilter.pl"
callers: ['gatk','freebayes','gatk_upper','gatk_lower','gatk_unfiltered','varscan','freebayes_unfiltered']
