#parameters to make graph to research the effect of different proportions on the accuracy of variant calling
reference: "/tudelft.net/staff-umbrella/YeastVariantCalling/wsung/IMBvariant/reference/chromosomes/CEN.PK113-7D_chr01_pilon.fa"
name: "chr1"
mutations: 200
repeats: 50
props: [[0.85,0.05,0.05,0.05],[0.70,0.15,0.10,0.05],[0.25,0.25,0.25,0.25],[0.4,0.4,0.1,0.1]]
f_cov: [20,50,100,200]
working_dir: "/tudelft.net/staff-umbrella/YeastVariantCalling/wsung/output"
rename_file: "/tudelft.net/staff-umbrella/YeastVariantCalling/wsung/BEP_pipeline/config/rename_chr.txt"
varscan_filter: "/tudelft.net/staff-umbrella/YeastVariantCalling/wsung/BEP_pipeline/workflow/scripts/fpfilter.pl"
callers: ['gatk','freebayes','gatk_upper','gatk_lower','gatk_unfiltered','varscan','freebayes_unfiltered']
experiment_name: "ploidy4"
