reference: "/tudelft.net/staff-umbrella/YeastVariantCalling/wsung/IMBvariant/reference/chromosomes/CEN.PK113-7D_chr01_pilon.fa"
name: "chr1"
mutations: 200
repeats: 10
f_cov: [20,20]
working_dir: "/tudelft.net/staff-umbrella/YeastVariantCalling/wsung"
rename_file: "/tudelft.net/staff-umbrella/YeastVariantCalling/wsung/BEP-pipeline/config/rename_chr.txt"
varscan_filter: "/tudelft.net/staff-umbrella/YeastVariantCalling/wsung/BEP-pipeline/workflow/scripts/fpfilter.pl"
ploidy: 2
